version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migration
    environment:
      - ConnectionStrings__BikesDb=User ID=root;Password=root;Host=db;Port=5432;Database=bikes_db;
    profiles:
      - default
  db:
    image: postgres:15.1
    container_name: bikes_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bikes_db
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "bikes_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - default
      - infra
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
    - PATH=/root/.dotnet/tools:$PATH
    - ConnectionStrings__BikesDb=User ID=root;Password=root;Host=db;Port=5432;Database=bikes_db;
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      /bin/sh -c "dotnet ef database update"
    profiles:
      - default
      - infra
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    profiles:
      - default
      - infra
volumes:
 db_data:
 minio_data:
