FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /app/api
COPY ./api/*.csproj ./
RUN dotnet restore

COPY ./api/ ./
